### ISSUE TITLE
Broken via Paper 1.21.4 (hard fork)

### ISSUE THREAD

**Issue by andrewkm** [BG-Software-LLC/WildLoaders#119] opened 2024-12-25 07:46 UTC
### Minecraft's Version

Paper 1.21.4 Build 34
(https://github.com/PaperMC/Paper/commit/d568e175ee74d1f5a73070a2e1714f5a34b39354)

### Plugin's Version

https://github.com/BG-Software-LLC/WildLoaders/commit/3e68804785112dcd3681d976c1610612b9ed849e
Latest commit via dev branch which states 1.21.4 support.

### Describe the bug

https://pastebin.com/raw/a5P9meUV

### To Reproduce

Place a loader, load one, etc.

### Additional Information

Looks like the hard fork broke WildLoaders. @o

**Comment by OmerBenGera** [comment] 2024-12-25 17:44
Duplicate of #118

**Closed by OmerBenGera** 2024-12-25 17:44 UTC
Labels: Pending
