### ISSUE TITLE
Loaders keep loading (even when removed) until the server entirely stopped

### ISSUE THREAD

**Issue by DrRotstein** [BG-Software-LLC/WildLoaders#11] opened 2021-03-30 09:22 UTC
So my problem is: Even when a loader gets removed (by breaking it or by the time), the chunks keep loading. You can't reload, the only way to stop them is to stop the entire server and then reboot it

**Comment by OmerBenGera** [comment] 2021-03-30 11:31
Duplicate of #9 , and it's already patched in latest dev build.
Next time, make sure you use the issues format as well.

**Closed by OmerBenGera** 2021-03-30 11:31 UTC
